#!/bin/bash

export COLOR_BLACK="#3d352a"
export COLOR_RED="#cd5c5c"
export COLOR_GREEN="#86af80"
export COLOR_BLUE="#3da89e"
export COLOR_MAGENTA="#deb887"
export COLOR_CYAN="#b0c4de"
export COLOR_WHITE="#bbaa99"
export COLOR_YELLOW="#e8ae5b"

export COLOR_LIGHT_BLACK="#554444"
export COLOR_LIGHT_RED="#CC5533"
export COLOR_LIGHT_GREEN="#88cc22"
export COLOR_LIGHT_BLUE="#87ceeb"
export COLOR_LIGHT_MAGENTA="#996600"
export COLOR_LIGHT_CYAN="#b0c4de"
export COLOR_LIGHT_WHITE="#ddccbb"
export COLOR_LIGHT_YELLOW="#ffa75d"

export COLOR_BACKGROUND="#1c1c1c"
export COLOR_FOREGROUND="#bbaa99"
